name: C Compilation CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile main.c
      run: gcc -g -o main main.c

  leaks:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    container:
      image: ghcr.io/${{ github.repository }}/c-valgrind:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile with debug symbols
      run: gcc -g -o main *.c

    - name: Check memory leaks
      run: valgrind --leak-check=full --error-exitcode=1 ./main